CREATE TABLE IF NOT EXIST exampleone(

ExampleOneID  BIGINT PRIMARY KEY,
Date DATE
);


CREATE TABLE IF NOT EXIST exampletwo(
ExampleTwoID BIGINT PRIMARY KEY,
ExampleOneID BIGINT FOREIGN KEY,
SomeCategoryTypeID VARCHAR(5)
SomeGroupID VARCHAR(2)  
DateIn DATE,
DateOut DATE,
Hours	  INTEGER
)


CREATE TABLE IF NOT EXIST examplethree(
ExampleThreeID PRIMARY KEY,
ExampleTwoID FOREIGN KEY,
ExampleOneID INTEGER,
START_DATE_RAW DATE,
END_DATE_RAW DATE,
DATE_IN_RAW DATE,
HOURS_RAW INTEGER
)
